# Generated by Django 5.2 on 2025-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.TextField()),
                ('password', models.TextField()),
                ('password_salt', models.TextField()),
            ],
        ),
    ]
